name: Build Dataset

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install ZSH
        run: |
          sudo apt-get update
          sudo apt-get --assume-yes install zsh
      - uses: s-weigand/setup-conda@v1
      - run: conda --version
      - run: |
          conda create -n py27 python=2.7
          source activate py27
          conda install pip
          pip install ujson

      - name: Downloading datasets
        run: |
          cd preprocess
          wget -q http://www.ark.cs.cmu.edu/personas/data/corenlp_plot_summaries.tar
          wget -q http://www.ark.cs.cmu.edu/mheilman/questions/SupersenseTagger-10-01-12.tar.gz
          wget -q http://www.ark.cs.cmu.edu/personas/data/MovieSummaries.tar.gz
          tar -xf corenlp_plot_summaries.tar
          tar -xf SupersenseTagger-10-01-12.tar.gz
          tar -xf MovieSummaries.tar.gz

      - name: Run preprocessing
        run: |
          cd preprocess
          source activate py27
          ./pipeline.sh

      - name: Inference
        run: |
          cd java
          source activate py27
          ./run.sh ./output.dir ../preprocess/all.data

      - uses: actions/upload-artifact@v3
        with:
          name: inferred-output
          path: java/output.dir/
          if-no-files-found: error

      - name: Discord Webhook Action
        if: always()
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: "End of the JOB"



